[tool.poetry]
name = "loan-anomaly-detection"
version = "0.1.0"
description = ""
authors = ["Beskardes, Salih <salih.beskardes@solactive.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
